name: Settingup CI/CD Pipeline for Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Installing-Dependencies:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: installing-all-Dependencies
      run: |
        pip install uv
        uv add numpy 

  build-docker-Image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  
  
